/***************************************************************
* Copyright (C) 2018
*    Computer Graphics Support Group of 30 Phys-Math Lyceum
***************************************************************/

/* FILE NAME  : MTH.H
* PURPOSE     : Ray tracing.
*               Math handle.
* PROGRAMMER  : AD6.
* LAST UPDATE : 24.07.2018.
* NOTE        : None.
*
* No part of this file may be changed without agreement of
* Computer Graphics Support Group of 30 Phys-Math Lyceum
*/


#ifndef __MTH_H_
#define __MTH_H_

#include "CAMERA.H"
#include "VEC.H"
#include "MATR.H"
#include "RAY.H"
#include "SOLVE4.H"

#endif /* __MTH_H_ */

/* End of 'mth.h' file */